version: "3.3"

services: 
  redis-slack-bot:
    build: 
      context: ./
    ports:
      - 80:80
    image:
      loudmouth01/public-redis-slack-bot-repo
    container_name: 
      redis-slack-bot-container
    restart:
      always
    env_file:
      - .env
    
