version: "3.3"

services: 
  redis-slack-bot:
    build: 
      context: ./
      target: redis-build
    ports:
      - 80:80
    image:
      redis-slack-bot-image
    container_name: 
      redis-slack-bot-container
    restart:
      unless-stopped
    env_file:
      - .env
    
